"use client"
import * as React from "react"
import { cryptoBackendClient } from "@/lib/crypto-backend"
import type { CryptoWalletDetails, CryptoWalletPackageDocument } from "@/lib/crypto-backend"
import { signSolanaIntent } from "@/lib/crypto-wallet"
const SOL = "So11111111111111111111111111111111111111112"
const USDC = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"
export function ModernJupiterPanel({ userId, wallet, packageValue }: { userId: string; wallet: CryptoWalletDetails; packageValue: CryptoWalletPackageDocument }) {
  const account = wallet.accounts.find(a => a.chainFamily === "solana" && a.state === "active")
  const [side, setSide] = React.useState<"buy"|"sell">("buy"); const [amount, setAmount] = React.useState(""); const [busy, setBusy] = React.useState(false); const [message, setMessage] = React.useState<string | null>(null)
  async function submit() { setBusy(true); setMessage(null); try { if (!account?.id) throw new Error("Modern Solana wallet is not ready"); const value = Number(amount); if (!(value > 0)) throw new Error("Enter a positive USDC amount"); const inputMint = side === "buy" ? USDC : SOL; const outputMint = side === "buy" ? SOL : USDC; const units = side === "buy" ? Math.round(value * 1e6) : Math.round(value * 1e9); const intent = await cryptoBackendClient.createModernSolanaSpotIntent({ inputMint, outputMint, amountBaseUnits: String(units), slippageBps: 100, idempotencyKey: crypto.randomUUID() }); const signed = await signSolanaIntent(userId, wallet.id, packageValue, intent, account.id); await cryptoBackendClient.submitIntent(intent.id, signed); setMessage("Jupiter swap submitted. Refresh balances after confirmation.") } catch (e) { setMessage(e instanceof Error ? e.message : "Jupiter swap failed") } finally { setBusy(false) } }
  return <div className="mt-4 rounded-xl border border-border p-3"><div className="mb-2 flex items-center justify-between"><h3 className="text-sm font-bold">Modern Solana spot</h3><span className="text-[11px] text-muted-foreground">Jupiter</span></div><div className="mb-2 grid grid-cols-2 gap-1 rounded-lg bg-surface-sunken p-1">{(["buy","sell"] as const).map(v => <button key={v} onClick={() => setSide(v)} className={`rounded-md py-2 text-xs font-semibold ${side === v ? "bg-primary text-primary-foreground" : "text-muted-foreground"}`}>{v === "buy" ? "Buy SOL" : "Sell SOL"}</button>)}</div><label className="block text-xs">{side === "buy" ? "USDC" : "SOL"} amount<input value={amount} onChange={e => setAmount(e.target.value)} className="mt-1 w-full rounded-lg border border-border bg-surface-sunken p-2.5" inputMode="decimal" placeholder="0.00" /></label>{message && <p className="mt-2 text-xs text-muted-foreground">{message}</p>}<button disabled={busy} onClick={submit} className="mt-3 w-full rounded-full bg-primary py-2.5 text-xs font-bold text-primary-foreground disabled:opacity-50">{busy ? "Preparing and signing…" : "Review Jupiter swap"}</button></div>
}
